#!/usr/bin/env bash
#find ip and replace, inside new file
cp /etc/hosts ~/hosts.new
sed -i '1i 8.8.8.8    facebook.com' ~/hosts.new
sed 's/127.0.0.1/127.0.0.2/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
